return function(hi, c)
  -- Semantic tokens
  hi('@lsp.type.class', { link = '@type' })
  hi('@lsp.type.comment', { link = '@comment' })
  hi('@lsp.type.decorator', { link = '@function' })
  hi('@lsp.type.enum', { link = '@type' })
  hi('@lsp.type.enumMember', { link = '@property' })
  hi('@lsp.type.event', { link = '@type' })
  hi('@lsp.type.function', { link = '@function' })
  hi('@lsp.type.interface', { link = '@type' })
  hi('@lsp.type.keyword', { link = '@keyword' })
  hi('@lsp.type.macro', { link = '@function.macro' })
  hi('@lsp.type.method', { link = '@function.method' })
  hi('@lsp.type.modifier', { link = '@keyword.modifier' })
  hi('@lsp.type.namespace', { link = '@module' })
  hi('@lsp.type.number', { link = '@number' })
  hi('@lsp.type.operator', { link = '@operator' })
  hi('@lsp.type.parameter', { link = '@variable.parameter' })
  hi('@lsp.type.property', { link = '@property' })
  hi('@lsp.type.regexp', { link = '@string.regexp' })
  hi('@lsp.type.string', { link = '@string' })
  hi('@lsp.type.struct', { link = '@type' })
  hi('@lsp.type.type', { link = '@type' })
  hi('@lsp.type.typeParameter', { link = '@type.definition' })
  hi('@lsp.type.variable', { link = '@variable' })
  hi('@lsp.type.generic', { fg = c.olive })

  hi('@lsp.mod.deprecated', { strikethrough = true })
  hi('@lsp.mod.readonly', { italic = true })
  hi('@lsp.mod.defaultLibrary', { link = '@variable.builtin' })

  -- LSP
  hi('LspReferenceText', { bg = c.bg_reference })
  hi('LspReferenceRead', { bg = c.bg_reference })
  hi('LspReferenceWrite', { bg = c.bg_reference_write, bold = true })
  hi('LspSignatureActiveParameter', { underline = true, sp = c.terracotta })
  hi('LspInlayHint', { link = 'LineNr' })
  hi('LspCodeLens', { fg = c.light_pebble })
  hi('LspCodeLensSeparator', { fg = c.pale_stone })
  hi('LspInfoBorder', { link = 'FloatBorder' })

  -- Diagnostics
  hi('DiagnosticError', { fg = c.coral })
  hi('DiagnosticWarn', { fg = c.honey })
  hi('DiagnosticInfo', { fg = c.sage })
  hi('DiagnosticHint', { fg = c.storm_blue })
  hi('DiagnosticOk', { fg = c.olive })

  hi('DiagnosticUnderlineError', { undercurl = true, sp = c.coral })
  hi('DiagnosticUnderlineWarn', { undercurl = true, sp = c.honey })
  hi('DiagnosticUnderlineInfo', { undercurl = true, sp = c.sage })
  hi('DiagnosticUnderlineHint', { undercurl = true, sp = c.storm_blue })

  hi('DiagnosticVirtualTextError', { fg = c.brick, bg = c.bg2 })
  hi('DiagnosticVirtualTextWarn', { fg = c.honey, bg = c.bg2 })
  hi('DiagnosticVirtualTextInfo', { fg = c.sage, bg = c.bg2 })
  hi('DiagnosticVirtualTextHint', { fg = c.storm_blue, bg = c.bg2 })

  hi('DiagnosticFloatingError', { fg = c.brick })
  hi('DiagnosticFloatingWarn', { fg = c.honey })
  hi('DiagnosticFloatingInfo', { fg = c.sage })
  hi('DiagnosticFloatingHint', { fg = c.storm_blue })

  hi('DiagnosticSignError', { fg = c.brick })
  hi('DiagnosticSignWarn', { fg = c.honey })
  hi('DiagnosticSignInfo', { fg = c.sage })
  hi('DiagnosticSignHint', { fg = c.storm_blue })

  hi('ErrorFloat', { fg = c.brick })
end
