return function(hi, c)
  -- treesitter-context
  hi('TreesitterContext', { fg = c.fg, bg = c.bg2 })

  -- gitsigns
  hi('GitSignsAdd', { fg = c.olive })
  hi('GitSignsChange', { fg = c.honey })
  hi('GitSignsDelete', { fg = c.brick })
  hi('GitSignsAddNr', { fg = c.olive })
  hi('GitSignsChangeNr', { fg = c.honey })
  hi('GitSignsDeleteNr', { fg = c.brick })
  hi('GitSignsAddLn', { bg = c.bg_green })
  hi('GitSignsChangeLn', { bg = c.bg_blue })
  hi('GitSignsDeleteLn', { bg = c.bg_red })

  -- todo-comments
  hi('TodoBgTODO', { bg = c.sage, fg = c.bg_dim, bold = true })
  hi('TodoFgTODO', { fg = c.sage, bold = true })
  hi('TodoSignTODO', { fg = c.sage, bold = true })
  hi('TodoBgFIX', { bg = c.coral, fg = c.bg_dim, bold = true })
  hi('TodoFgFIX', { fg = c.coral, bold = true })
  hi('TodoSignFIX', { fg = c.coral, bold = true })
  hi('TodoBgHACK', { bg = c.honey, fg = c.bg_dim, bold = true })
  hi('TodoFgHACK', { fg = c.honey, bold = true })
  hi('TodoSignHACK', { fg = c.honey, bold = true })
  hi('TodoBgWARN', { bg = c.honey, fg = c.bg_dim, bold = true })
  hi('TodoFgWARN', { fg = c.honey, bold = true })
  hi('TodoSignWARN', { fg = c.honey, bold = true })
  hi('TodoBgPERF', { bg = c.dusty_purple, fg = c.bg_dim, bold = true })
  hi('TodoFgPERF', { fg = c.dusty_purple, bold = true })
  hi('TodoSignPERF', { fg = c.dusty_purple, bold = true })
  hi('TodoBgNOTE', { bg = c.storm_blue, fg = c.bg_dim, bold = true })
  hi('TodoFgNOTE', { fg = c.storm_blue, bold = true })
  hi('TodoSignNOTE', { fg = c.storm_blue, bold = true })
  hi('TodoBgTEST', { bg = c.dusty_purple, fg = c.bg_dim, bold = true })
  hi('TodoFgTEST', { fg = c.dusty_purple, bold = true })
  hi('TodoSignTEST', { fg = c.dusty_purple, bold = true })

  -- yanky
  hi('YankyPut', { bg = c.bg_yank })
  hi('YankyYanked', { bg = c.bg_yank })

  -- blink.pairs
  hi('BlinkPairsWarm1', { fg = c.warm_orange })
  hi('BlinkPairsWarm2', { fg = c.river_stone })

  -- neo-tree
  hi('NeoTreeNormal', { fg = c.fg, bg = c.bg_dim })
  hi('NeoTreeNormalNC', { fg = c.fg, bg = c.bg_dim })
  hi('NeoTreeEndOfBuffer', { fg = c.bg_dim, bg = c.bg_dim })
  hi('NeoTreeWinSeparator', { fg = c.bg, bg = c.bg })
  hi('NeoTreeCursorLine', { bg = c.bg })
  hi('NeoTreeDirectoryName', { fg = c.olive })
  hi('NeoTreeDirectoryIcon', { fg = c.honey })
  hi('NeoTreeFileName', { fg = c.fg })
  hi('NeoTreeFileIcon', { fg = c.stone_grey })
  hi('NeoTreeRootName', { fg = c.warm_orange, bold = true })
  hi('NeoTreeGitAdded', { fg = c.olive })
  hi('NeoTreeGitModified', { fg = c.honey })
  hi('NeoTreeGitDeleted', { fg = c.brick })
  hi('NeoTreeGitConflict', { fg = c.coral, bold = true })
  hi('NeoTreeGitUntracked', { fg = c.dusty_purple })
  hi('NeoTreeIndentMarker', { fg = c.pale_stone })

  -- which-key
  hi('WhichKey', { fg = c.brick })
  hi('WhichKeyGroup', { fg = c.olive })
  hi('WhichKeySeparator', { fg = c.light_pebble })
  hi('WhichKeyDesc', { fg = c.storm_blue })
  hi('WhichKeyFloat', { bg = c.bg1 })
  hi('WhichKeyBorder', { fg = c.light_pebble, bg = c.bg1 })
  hi('WhichKeyValue', { fg = c.light_pebble })

  -- lazy.nvim
  hi('LazyH1', { fg = c.bg, bg = c.olive, bold = true })
  hi('LazyButton', { fg = c.light_pebble, bg = c.bg2 })
  hi('LazyButtonActive', { fg = c.bg, bg = c.brick, bold = true })
  hi('LazySpecial', { fg = c.honey })
  hi('LazyReasonPlugin', { fg = c.olive })
  hi('LazyReasonEvent', { fg = c.honey })
  hi('LazyReasonKeys', { fg = c.dusty_purple })
  hi('LazyReasonCmd', { fg = c.storm_blue })

  -- trouble
  hi('TroubleNormal', { fg = c.fg, bg = c.bg_dim })
  hi('TroubleNormalNC', { fg = c.fg, bg = c.bg_dim })
  hi('TroubleCount', { fg = c.bg, bg = c.terracotta, bold = true })

  -- flash
  hi('FlashMatch', { fg = c.fg, bg = c.bg_yellow })
  hi('FlashCurrent', { fg = c.bg, bg = c.olive, bold = true })
  hi('FlashLabel', { fg = c.bg, bg = c.brick, bold = true })

  -- noice
  hi('NoiceCmdlinePopup', { fg = c.fg, bg = c.bg2 })
  hi('NoiceCmdlinePopupBorder', { fg = c.light_pebble, bg = c.bg2 })
  hi('NoiceCmdlineIcon', { fg = c.olive })
  hi('NoiceMini', { fg = c.fg, bg = c.bg2 })

  -- blink.cmp
  hi('BlinkCmpMenu', { fg = c.fg, bg = c.bg2 })
  hi('BlinkCmpMenuBorder', { fg = c.light_pebble, bg = c.bg2 })
  hi('BlinkCmpMenuSelection', { fg = c.bg, bg = c.statusline1 })
  hi('BlinkCmpScrollBarThumb', { bg = c.river_stone })
  hi('BlinkCmpScrollBarGutter', { bg = c.bg2 })
  hi('BlinkCmpLabel', { fg = c.fg })
  hi('BlinkCmpLabelDeprecated', { fg = c.light_pebble, strikethrough = true })
  hi('BlinkCmpLabelMatch', { fg = c.olive, bold = true })
  hi('BlinkCmpLabelDetail', { fg = c.light_pebble })
  hi('BlinkCmpLabelDescription', { fg = c.light_pebble })
  hi('BlinkCmpKind', { fg = c.honey })
  hi('BlinkCmpKindText', { fg = c.fg })
  hi('BlinkCmpKindMethod', { fg = c.olive })
  hi('BlinkCmpKindFunction', { fg = c.blue_stone })
  hi('BlinkCmpKindConstructor', { fg = c.olive })
  hi('BlinkCmpKindField', { fg = c.storm_blue })
  hi('BlinkCmpKindVariable', { fg = c.deep_forest })
  hi('BlinkCmpKindClass', { fg = c.sage_green })
  hi('BlinkCmpKindInterface', { fg = c.sage_green })
  hi('BlinkCmpKindModule', { fg = c.honey })
  hi('BlinkCmpKindProperty', { fg = c.storm_blue })
  hi('BlinkCmpKindUnit', { fg = c.dusty_purple })
  hi('BlinkCmpKindValue', { fg = c.earth_brown })
  hi('BlinkCmpKindEnum', { fg = c.sage_green })
  hi('BlinkCmpKindKeyword', { fg = c.terracotta })
  hi('BlinkCmpKindSnippet', { fg = c.aqua })
  hi('BlinkCmpKindColor', { fg = c.honey })
  hi('BlinkCmpKindFile', { fg = c.olive })
  hi('BlinkCmpKindReference', { fg = c.aqua })
  hi('BlinkCmpKindFolder', { fg = c.olive })
  hi('BlinkCmpKindEnumMember', { fg = c.storm_blue })
  hi('BlinkCmpKindConstant', { fg = c.earth_brown })
  hi('BlinkCmpKindStruct', { fg = c.sage_green })
  hi('BlinkCmpKindEvent', { fg = c.warm_orange })
  hi('BlinkCmpKindOperator', { fg = c.charcoal })
  hi('BlinkCmpKindTypeParameter', { fg = c.honey })
  hi('BlinkCmpDoc', { fg = c.fg, bg = c.bg2 })
  hi('BlinkCmpDocBorder', { fg = c.light_pebble, bg = c.bg2 })
  hi('BlinkCmpDocSeparator', { fg = c.light_pebble, bg = c.bg2 })
  hi('BlinkCmpSignatureHelp', { fg = c.fg, bg = c.bg2 })
  hi('BlinkCmpSignatureHelpBorder', { fg = c.light_pebble, bg = c.bg2 })
  hi('BlinkCmpSignatureHelpActiveParameter', { underline = true, sp = c.terracotta })
  hi('BlinkCmpGhostText', { fg = c.bg5 })

  -- fzf-lua
  hi('FzfLuaNormal', { fg = c.fg, bg = c.bg_dim })
  hi('FzfLuaBorder', { fg = c.light_pebble, bg = c.bg_dim })
  hi('FzfLuaTitle', { fg = c.warm_orange, bold = true })
  hi('FzfLuaPreviewNormal', { fg = c.fg, bg = c.bg })
  hi('FzfLuaPreviewBorder', { fg = c.light_pebble, bg = c.bg })
  hi('FzfLuaPreviewTitle', { fg = c.warm_orange, bold = true })
  hi('FzfLuaCursorLine', { bg = c.bg1 })
  hi('FzfLuaCursorLineNr', { fg = c.light_pebble, bg = c.bg1 })
  hi('FzfLuaSearch', { fg = c.bg, bg = c.olive })
  hi('FzfLuaHeaderBind', { fg = c.olive })
  hi('FzfLuaHeaderText', { fg = c.warm_orange })
  hi('FzfLuaPathLineNr', { fg = c.light_pebble })
  hi('FzfLuaPathColNr', { fg = c.light_pebble })
  hi('FzfLuaBufName', { fg = c.olive })
  hi('FzfLuaBufNr', { fg = c.dusty_purple })
  hi('FzfLuaBufFlagCur', { fg = c.olive })
  hi('FzfLuaBufFlagAlt', { fg = c.storm_blue })
  hi('FzfLuaFzfNormal', { fg = c.fg })
  hi('FzfLuaFzfCursorLine', { bg = c.bg1 })
  hi('FzfLuaFzfMatch', { fg = c.olive, bold = true })
  hi('FzfLuaFzfBorder', { fg = c.light_pebble })
  hi('FzfLuaFzfGutter', { bg = c.bg_dim })
  hi('FzfLuaFzfPointer', { fg = c.brick })
  hi('FzfLuaFzfMarker', { fg = c.honey })
  hi('FzfLuaFzfPrompt', { fg = c.olive })
  hi('FzfLuaFzfQuery', { fg = c.fg })

  -- nvim-dap
  hi('DapBreakpoint', { fg = c.brick })
  hi('DapBreakpointCondition', { fg = c.honey })
  hi('DapLogPoint', { fg = c.storm_blue })
  hi('DapStopped', { fg = c.olive, bg = c.bg_yellow })
  hi('DapBreakpointRejected', { fg = c.light_pebble })

  -- nvim-dap-ui
  hi('DapUIScope', { fg = c.aqua })
  hi('DapUIType', { fg = c.sage_green })
  hi('DapUIValue', { fg = c.fg })
  hi('DapUIVariable', { fg = c.deep_forest })
  hi('DapUIModifiedValue', { fg = c.honey, bold = true })
  hi('DapUIDecoration', { fg = c.light_pebble })
  hi('DapUIThread', { fg = c.olive })
  hi('DapUIStoppedThread', { fg = c.brick })
  hi('DapUISource', { fg = c.dusty_purple })
  hi('DapUILineNumber', { fg = c.bg5 })
  hi('DapUIFloatNormal', { fg = c.fg, bg = c.bg2 })
  hi('DapUIFloatBorder', { fg = c.light_pebble, bg = c.bg2 })
  hi('DapUIWatchesEmpty', { fg = c.light_pebble })
  hi('DapUIWatchesValue', { fg = c.olive })
  hi('DapUIWatchesError', { fg = c.brick })
  hi('DapUIBreakpointsPath', { fg = c.storm_blue })
  hi('DapUIBreakpointsInfo', { fg = c.olive })
  hi('DapUIBreakpointsCurrentLine', { fg = c.olive, bold = true })
  hi('DapUIBreakpointsDisabledLine', { fg = c.light_pebble })
  hi('DapUICurrentFrameName', { fg = c.olive, bold = true })
  hi('DapUIStepOver', { fg = c.storm_blue })
  hi('DapUIStepInto', { fg = c.storm_blue })
  hi('DapUIStepBack', { fg = c.storm_blue })
  hi('DapUIStepOut', { fg = c.storm_blue })
  hi('DapUIStop', { fg = c.brick })
  hi('DapUIPlayPause', { fg = c.olive })
  hi('DapUIRestart', { fg = c.olive })
  hi('DapUIUnavailable', { fg = c.light_pebble })

  -- neotest
  hi('NeotestPassed', { fg = c.olive })
  hi('NeotestFailed', { fg = c.coral })
  hi('NeotestRunning', { fg = c.honey })
  hi('NeotestSkipped', { fg = c.stone_grey })
  hi('NeotestTest', { fg = c.fg })
  hi('NeotestNamespace', { fg = c.aqua })
  hi('NeotestFile', { fg = c.storm_blue })
  hi('NeotestDir', { fg = c.olive })
  hi('NeotestAdapterName', { fg = c.warm_orange, bold = true })
  hi('NeotestTarget', { fg = c.brick })
  hi('NeotestMarked', { fg = c.honey, bold = true })
  hi('NeotestFocused', { underline = true })
  hi('NeotestIndent', { fg = c.pale_stone })
  hi('NeotestExpandMarker', { fg = c.light_pebble })
  hi('NeotestWatching', { fg = c.honey })
  hi('NeotestUnknown', { fg = c.light_pebble })
  hi('NeotestBorder', { fg = c.light_pebble })

  -- render-markdown
  hi('RenderMarkdownH1', { fg = c.warm_orange, bold = true })
  hi('RenderMarkdownH2', { fg = c.olive, bold = true })
  hi('RenderMarkdownH3', { fg = c.honey, bold = true })
  hi('RenderMarkdownH4', { fg = c.aqua, bold = true })
  hi('RenderMarkdownH5', { fg = c.storm_blue, bold = true })
  hi('RenderMarkdownH6', { fg = c.dusty_purple, bold = true })
  hi('RenderMarkdownH1Bg', { bg = c.bg_yellow })
  hi('RenderMarkdownH2Bg', { bg = c.bg_green })
  hi('RenderMarkdownH3Bg', { bg = c.bg_yellow })
  hi('RenderMarkdownH4Bg', { bg = c.bg_blue })
  hi('RenderMarkdownH5Bg', { bg = c.bg_blue })
  hi('RenderMarkdownH6Bg', { bg = c.bg_red })
  hi('RenderMarkdownCode', { bg = c.bg1 })
  hi('RenderMarkdownCodeInline', { bg = c.bg1 })
  hi('RenderMarkdownCodeBorder', { fg = c.light_pebble, bg = c.bg1 })
  hi('RenderMarkdownBullet', { fg = c.storm_blue })
  hi('RenderMarkdownChecked', { fg = c.olive })
  hi('RenderMarkdownUnchecked', { fg = c.sage })
  hi('RenderMarkdownQuote', { fg = c.light_pebble })
  hi('RenderMarkdownDash', { fg = c.bg4 })
  hi('RenderMarkdownLink', { fg = c.aqua })
  hi('RenderMarkdownMath', { fg = c.warm_amber })
  hi('RenderMarkdownTableHead', { fg = c.olive })
  hi('RenderMarkdownTableRow', { fg = c.fg })

  -- nvim-ufo
  hi('UfoFoldedEllipsis', { fg = c.stone_grey })

  -- telescope
  hi('TelescopeNormal', { fg = c.fg, bg = c.bg_dim })
  hi('TelescopeBorder', { fg = c.light_pebble, bg = c.bg_dim })
  hi('TelescopeTitle', { fg = c.warm_orange, bold = true })
  hi('TelescopePromptNormal', { fg = c.fg, bg = c.bg })
  hi('TelescopePromptBorder', { fg = c.light_pebble, bg = c.bg })
  hi('TelescopePromptTitle', { fg = c.warm_orange, bold = true })
  hi('TelescopePromptPrefix', { fg = c.olive })
  hi('TelescopePromptCounter', { fg = c.light_pebble })
  hi('TelescopeResultsNormal', { fg = c.fg, bg = c.bg_dim })
  hi('TelescopeResultsBorder', { fg = c.light_pebble, bg = c.bg_dim })
  hi('TelescopeResultsTitle', { fg = c.warm_orange, bold = true })
  hi('TelescopePreviewNormal', { fg = c.fg, bg = c.bg })
  hi('TelescopePreviewBorder', { fg = c.light_pebble, bg = c.bg })
  hi('TelescopePreviewTitle', { fg = c.warm_orange, bold = true })
  hi('TelescopeSelection', { bg = c.bg1 })
  hi('TelescopeSelectionCaret', { fg = c.brick })
  hi('TelescopeMultiSelection', { fg = c.honey })
  hi('TelescopeMultiIcon', { fg = c.honey })
  hi('TelescopeMatching', { fg = c.olive, bold = true })

  -- diffview
  hi('DiffviewFilePanelTitle', { fg = c.warm_orange, bold = true })
  hi('DiffviewFilePanelCounter', { fg = c.dusty_purple })
  hi('DiffviewFilePanelFileName', { fg = c.fg })
  hi('DiffviewFilePanelPath', { fg = c.light_pebble })
  hi('DiffviewFilePanelRootPath', { fg = c.warm_orange })
  hi('DiffviewFilePanelInsertions', { fg = c.olive })
  hi('DiffviewFilePanelDeletions', { fg = c.brick })
  hi('DiffviewDiffAdd', { bg = c.bg_green })
  hi('DiffviewDiffDelete', { bg = c.bg_red })
  hi('DiffviewDiffChange', { bg = c.bg_blue })
end
