return function(hi, c)
  -- Vim syntax
  hi('Comment', { fg = c.comment, italic = true })
  hi('String', { fg = c.moss })
  hi('Character', { fg = c.moss })
  hi('Number', { fg = c.plum })
  hi('Boolean', { fg = c.plum })
  hi('Float', { fg = c.plum })

  hi('Constant', { fg = c.aqua })
  hi('Identifier', { fg = c.storm_blue })
  hi('Function', { fg = c.olive })

  hi('Statement', { fg = c.brick })
  hi('Conditional', { fg = c.brick })
  hi('Repeat', { fg = c.brick })
  hi('Label', { fg = c.warm_orange })
  hi('Operator', { fg = c.warm_orange })
  hi('Keyword', { fg = c.brick })
  hi('Exception', { fg = c.brick })

  hi('PreProc', { fg = c.plum })
  hi('Include', { fg = c.plum })
  hi('Define', { fg = c.plum })
  hi('Macro', { fg = c.aqua })
  hi('PreCondit', { fg = c.plum })

  hi('Type', { fg = c.honey })
  hi('StorageClass', { fg = c.warm_orange })
  hi('Structure', { fg = c.warm_orange })
  hi('Typedef', { fg = c.brick })

  hi('Special', { fg = c.honey })
  hi('SpecialChar', { fg = c.honey })
  hi('Tag', { fg = c.warm_orange })
  hi('Delimiter', { fg = c.fg })
  hi('SpecialComment', { fg = c.comment, italic = true })
  hi('Debug', { fg = c.warm_orange })

  hi('Underlined', { underline = true })
  hi('Bold', { bold = true })
  hi('Italic', { italic = true })
  hi('Error', { fg = c.brick })
  hi('Todo', { fg = c.bg, bg = c.storm_blue, bold = true })

  -- Named groups referenced by other highlight links
  hi('Red', { fg = c.red })
  hi('Orange', { fg = c.orange })
  hi('Purple', { fg = c.purple })
  hi('PurpleItalic', { fg = c.plum })

  -- Treesitter
  hi('@variable', { fg = c.deep_forest })
  hi('@variable.builtin', { fg = c.weathered_oak })
  hi('@variable.parameter', { fg = c.clay })
  hi('@variable.member', { fg = c.storm_blue })

  hi('@constant', { fg = c.earth_brown })
  hi('@constant.builtin', { fg = c.plum })
  hi('@constant.macro', { fg = c.plum })

  hi('@module', { fg = c.honey })
  hi('@module.builtin', { fg = c.honey })
  hi('@label', { fg = c.warm_orange })

  hi('@string', { fg = c.moss })
  hi('@string.documentation', { fg = c.comment, italic = true })
  hi('@string.escape', { fg = c.olive })
  hi('@string.regexp', { fg = c.olive })
  hi('@string.special', { fg = c.honey })
  hi('@string.special.symbol', { fg = c.aqua })
  hi('@string.special.url', { fg = c.storm_blue, underline = true })
  hi('@string.special.path', { fg = c.storm_blue })

  hi('@character', { fg = c.aqua })
  hi('@character.special', { fg = c.aqua })
  hi('@boolean', { fg = c.earth_brown })
  hi('@number', { fg = c.dark_amber })
  hi('@number.float', { fg = c.dried_rose })

  hi('@type', { fg = c.sage_green })
  hi('@type.builtin', { fg = c.honey })
  hi('@type.definition', { fg = c.honey })
  hi('@type.qualifier', { fg = c.warm_orange })

  hi('@attribute', { fg = c.plum })
  hi('@attribute.builtin', { fg = c.plum })
  hi('@property', { fg = c.storm_blue })

  hi('@function', { fg = c.blue_stone })
  hi('@function.builtin', { fg = c.bark })
  hi('@function.call', { fg = c.olive })
  hi('@function.macro', { fg = c.olive })
  hi('@function.method', { fg = c.olive })
  hi('@function.method.call', { fg = c.olive })
  hi('@constructor', { fg = c.olive })

  hi('@keyword', { fg = c.terracotta })
  hi('@keyword.coroutine', { fg = c.brick })
  hi('@keyword.function', { fg = c.brick })
  hi('@keyword.operator', { fg = c.warm_orange })
  hi('@keyword.import', { fg = c.brick })
  hi('@keyword.type', { fg = c.terracotta })
  hi('@keyword.modifier', { fg = c.warm_orange })
  hi('@keyword.repeat', { fg = c.brick })
  hi('@keyword.return', { fg = c.brick })
  hi('@keyword.debug', { fg = c.warm_orange })
  hi('@keyword.exception', { fg = c.brick })
  hi('@keyword.conditional', { fg = c.brick })
  hi('@keyword.conditional.ternary', { fg = c.brick })
  hi('@keyword.directive', { fg = c.plum })
  hi('@keyword.directive.define', { fg = c.plum })
  hi('@keyword.storage', { fg = c.warm_orange })

  hi('@operator', { fg = c.charcoal })
  hi('@punctuation', { fg = c.stone_grey })
  hi('@punctuation.bracket', { fg = c.stone_grey })
  hi('@punctuation.delimiter', { fg = c.lichen })
  hi('@punctuation.special', { fg = c.twig })

  hi('@comment', { fg = c.comment, italic = true })
  hi('@comment.documentation', { fg = c.comment, italic = true })
  hi('@comment.error', { fg = c.coral, bold = true })
  hi('@comment.warning', { fg = c.honey, bold = true })
  hi('@comment.todo', { fg = c.sage, bold = true })
  hi('@comment.note', { fg = c.storm_blue, bold = true })

  hi('@markup.strong', { bold = true })
  hi('@markup.italic', { italic = true })
  hi('@markup.strikethrough', { strikethrough = true })
  hi('@markup.underline', { underline = true })
  hi('@markup.heading', { fg = c.warm_orange, bold = true })
  hi('@markup.heading.1', { fg = c.warm_orange, bold = true })
  hi('@markup.heading.2', { fg = c.olive, bold = true })
  hi('@markup.heading.3', { fg = c.honey, bold = true })
  hi('@markup.heading.4', { fg = c.aqua, bold = true })
  hi('@markup.heading.5', { fg = c.storm_blue, bold = true })
  hi('@markup.heading.6', { fg = c.plum, bold = true })
  hi('@markup.quote', { fg = c.light_pebble, italic = true })
  hi('@markup.math', { fg = c.dark_amber })
  hi('@markup.link', { fg = c.aqua })
  hi('@markup.link.label', { fg = c.aqua })
  hi('@markup.link.url', { fg = c.storm_blue, underline = true })
  hi('@markup.raw', { fg = c.olive })
  hi('@markup.raw.block', { fg = c.fg })
  hi('@markup.list', { fg = c.storm_blue })
  hi('@markup.list.checked', { fg = c.olive, bold = true })
  hi('@markup.list.unchecked', { fg = c.sage, bold = true })

  hi('@tag', { fg = c.warm_orange })
  hi('@tag.attribute', { fg = c.olive })
  hi('@tag.delimiter', { fg = c.olive })
  hi('@tag.builtin', { fg = c.warm_orange })

  hi('@diff.plus', { fg = c.olive })
  hi('@diff.minus', { fg = c.brick })
  hi('@diff.delta', { fg = c.storm_blue })

  -- Legacy @text aliases
  hi('@text.todo', { fg = c.sage, bold = true })
  hi('@text.note', { fg = c.storm_blue, bold = true })
  hi('@text.warning', { fg = c.honey, bold = true })
  hi('@text.danger', { fg = c.coral, bold = true })
  hi('@text.todo.unchecked', { fg = c.sage, bold = true })
  hi('@text.todo.checked', { fg = c.olive, bold = true })
end
